from .victorian_furniture import VictorianFurnitureChair
from .victorian_furniture import VictorianFurnitureSofa
from .victorian_furniture import VictorianFurnitureTable

from .mordern_furniture import MordernFurnitureChair
from .mordern_furniture import MordernFurnitureSofa
from .mordern_furniture import MordernFurnitureTable